### ISSUE TITLE
run logs

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#12]
for run logs, let's give this a try:

- if last run succeeded: ✅ 2017-07-03
- if last run was first failure: ⚠️ 2017-07-03 (on hover say "last run failed")
- if there have been multiple failures in a row: ❌ 2017-07-03 (on hover say "last X runs failed")

let me know if I'm misremembering what we settled on @mileswwatkins @hiteshgarg14

**Comment by hiteshgarg14** [comment]
Now #11 includes this info. :)
