### ISSUE TITLE
tests / code quality / ci

### ISSUE THREAD

**Issue by jmcarp** [openstates/admintools#14]
Even though this is a new project, it's never too early to write unit tests and think about code hygiene! Here are a few suggestions that IMO should happen sooner rather than later. I'd be happy to help with any of these.

- [x] Add unit tests. Even a handful of tests can be very useful, since they'll force us to pick a test runner (hopefully pytest) and make it easy to add more tests in the future.
- [x] Add code style checks. Ideally this would include a tool like code climate, but flake8 + travis would be a good start.
- [ ] Add a dependency checker, like gemnasium or greenkeeper.

In the future, consider using tools like https://github.com/pydanny/cookiecutter-django to take care of lots of these issues automatically.

**Comment by mileswwatkins** [comment]
@hiteshgarg14, this is one thing that I'd like you to add over the next week (at least setting up Travis  and applying `flake8` linting therein, similar to https://github.com/openstates/openstates/blob/master/.travis.yml#L5). Dependency checking and unit tests would be great as well.
