### ISSUE TITLE
Add legislator-retirement tool

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#22]
Related to https://github.com/openstates/admintools/issues/21, we'll need a tool to "retire" legislators who've left their post, due to retirement, death, etc.

**Comment by hiteshgarg14** [comment]
@mileswwatkins 
PR #28 includes most of the important files which we need like views.py etc..  So I can't go for a separate PR for this issue. 

_should I implement this tool in that PR or wait until you merge it?_

**Comment by hiteshgarg14** [comment]
@jamesturk  okay cool :)
I will use second branch for this also :+1:
