### ISSUE TITLE
Design how we'll apply admin patches to the data

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#23]
Some options:

- Write directly to the database, and have a way to mark the admin-edited fields as "locked"?
- Have a table of patches that get applied after each scrape?
- Have a series of JSON patch files that get applied after each scrape, and archived somewhere public (like a dump on S3)?

This is necessary before we can really use the admin interface for much, besides retiring/merging.

cc @hiteshgarg14 @jamesturk, maybe let's talk about this tomorrow?

**Comment by hiteshgarg14** [comment]
my vote is for _having a table of patches that get applied after each scrape._

**Comment by jamesturk** [comment]
pretty sure that my vote is the same

**Comment by jamesturk** [comment]
closing this one since it is covered in #6 and #25
