### ISSUE TITLE
examples for patch-apply logic

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#25]
reminder for myself to write these

**Comment by jamesturk** [comment]
OK so this is going to be a long one, let's look at some examples.  Assume we start with an empty DB.

Scrape 1:
* finds ocd-person/123 w/ photo_url=https://example.com/bad
* creates ocd-person/123

Admin action 1:
* add a Patch object: Patch(ocd-person/123, field='photo_url', old='https://example.com/bad', new='https://example.com/good', ...)  (we'll call this patch 1)
* at this point, **nothing has been changed in the Person table** 
* TODO: revisit this, it might make sense to apply these immediately upon approval, but for now let's ignore this item
* this patch is now approved (either automatically b/c it was admin or by an admin after being added)

Scrape 2:
* finds ocd-person/123 w/ photo_url=https://example.com/bad
* at import time, we find that an 'approved' patch-1 exists for ocd-person/123
   * we look to make sure the scraped value for photo_url matches https://example.com/bad, which it does
   * we therefore replace the photo_url, so ocd-person/123 is saved w/ https://example.com/good
* at this point, ocd-person/123 has correct data

... time goes by, let's assume scrapes 3-10 have the same result as scrape 2, each time replacing the value ...

Scrape 11:
* finds ocd-person/123 w/ photo_url=https://example.com/new
* at import time, we find that patch-1 exists for ocd-person/123
   * we look to make sure the scraped value for photo_url matches https://example.com/bad, which it *does not*
   * patch-1 is marked as 'deprecated' and will not be applied or considered again
* at this point, ocd-person/123 has photo_url=https://example.com/new (matching the site)
* if this is incorrect, someone can create a new patch (patch-2) 

future TODO: 
* should it be possible to revive patch-1 at any point?
* what if on Scrape-11 we found photo_url=https://example.com/good (special case, where the patch is especially redundant), do we do anything special?

**Comment by jamesturk** [comment]
@mileswwatkins for review

**Comment by mileswwatkins** [comment]
Looks good to me! I think we could even skip having an `old` column, and instead just check if there's a difference between the scraped value and the database value. Or is that not feasible @jamesturk?

**Comment by jamesturk** [comment]
we want the old column to see if the expected broken value changed, unless
I'm misunderstanding?

**Comment by mileswwatkins** [comment]
My thought was:

- load scraped value and patch value into memory
- load current-database value into memory
- if scraped and current-db are the same, use the patch
- if scraped and current-db are different, use scraped, and mark patch as obsolete

**Comment by jamesturk** [comment]
the current db value will be the corrected value after first patch, then if
we mark it as obsolete then it'll revert next time

On Jul 5, 2017 22:45, "Miles Watkins" <notifications@github.com> wrote:

My thought was:

   - load scraped value and patch value into memory
   - load current-database value into memory
   - if scraped and current-db are the same, use the patch
   - if scraped and current-db are different, use scraped, and mark patch
   as obsolete

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openstates/admintools/issues/25#issuecomment-313280445>,
or mute the thread

**Comment by jamesturk** [comment]
@hiteshgarg14 wanted to make sure to ping you on this so we could discuss
