### ISSUE TITLE
Refocus data quality type-specific pages on _actionability_

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#26]
The admin tool shouldn't be about browsing the data, as much as it should be about 1) identifying problems and 2) being able to fix (or at least diagnose) them manually. So, for example, the table of legislators with missing photos should have a way for the admin to type in the photo URLs directly; the table of VoteEvents with bad counts should include the two (different) counts and a link to the source URL for that VoteEvent, so that the admin can determine what the problem may be; if a committee has no memberships, include a button to delete that committee from the database if the admin determines that it doesn't exist anymore; if a voter is unmatched, drive the user towards the name matching tool; etc. Basically, the goal is to make all of these lists as actionable as possible.

Spun off of https://github.com/openstates/admintools/pull/16#issuecomment-312930625

**Comment by mileswwatkins** [comment]
For some data quality types, this is blocked by https://github.com/openstates/admintools/issues/23 and https://github.com/openstates/admintools/issues/25, but we can design and add the admin _interface_ for now, if you'd like @hiteshgarg14. And then once we resolve those two issues then you can actually implement the functionality.

**Comment by hiteshgarg14** [comment]
> the table of VoteEvents with bad counts should include the **two (different) counts** and a link to the source URL for that VoteEvent, so that the admin can determine what the problem may be

what should be the  `two (different) counts` from these choices?
[`Excused` and `Absent` may be??]
```
VOTE_OPTION_CHOICES = (
    ('yes', 'Yes'),
    ('no', 'No'),
    ('absent', 'Absent'),
    ('abstain', 'Abstain'),
    ('not voting', 'Not Voting'),
    ('paired', 'Paired'),
    ('excused', 'Excused'),

    # Only for open states.
    ('other', 'Other'),
)
```

**Comment by hiteshgarg14** [comment]
Okay! Before moving on just want to be confirmed that I am going in right direction. so below is the flow for admin patches of `missing` items. so please give some comments about my approach. can I go ahead or anything else you want to modify. 

@mileswwatkins @jamesturk 

(added a `SOURCES` column so that admin can directly find related links.)

### Bill Related Issues
   1. For *Missing Actions*, *Missing Sponsors* & *Missing Versions*  
        - When the admin clicks on a bill from the table then redirect admin to a new page where `BillAction` or `BillSponsorship` or `BillVersion`  *ModalForm*  will be shown.
   2. *unmatched-person-sponsor* & *unmatched-org-sponsor* 
        - skip for now until we have a working `name resolution tool`

### VoteEvent Related Issues

   1. For *Missing Bill*
         - Instead of motion text, there will a dropdown with options of all the bills related to that jurisdiction. when the user selects one and hit submit then that bill will be attached to related vote event.
   2. For *Missing Counts* & *Bad Counts*
         - please refer above [comment](https://github.com/openstates/admintools/issues/26#issuecomment-313775750). I am confused about what fields to show there on the table or we should go for displaying all options.
   3. For *Unmatched Voter*
       - skip for now until we have a working `name resolution tool`
   4. For *Missing Voters*
       - redirect admin to a new page where `PersonVote` *ModalForm* will be shown to add multiple voters.

### Organization Related Issues

  1. Introduced a `check box` to select multiple organization and bulk delete them.

### Person Issues

  1. please refer PR #28 

### Membership Related Issues

   1. skip for now until we have a working `name resolution tool`

**Comment by jamesturk** [comment]
Bill:
1. can you clarify what you mean here?   I think these should be read-only in general
2. yes, we'll revisit this

VoteEvent:

1. I don't think we should do this, the fix should probably be in the scraper so let's not have an action for this case.
2. if counts are missing there's nothing to show / if counts are wrong we should show which ones are wrong (i.e. "- there are 12 yes voters but yes_count=0, - there are 22 no voters but no_count=20)
3. yes
4. this too should be left read-only, I don't think people should be manually entering vote data, we want to fix these in the scraper

Organization:
- yes I think that makes sense, individual delete buttons might be easier and that's fine too 

& I'll review PR #28 soon

**Comment by hiteshgarg14** [comment]
Bill:

1. For eg, if admin wants to add missing actions to a bill. then we can show a `BillAction ModelForm` on a new page. where admin can add more than one actions (admin can fill more than one BillAction form by clicking add/remove buttons).  
but if you think these should be read-only in general then it's cool :)

VoteEvent:

1. according to `vote_event importer` `Bad Count` means vote event which has `option=other`. [link](https://github.com/openstates/admintools/blob/master/admintools/importers/vote_events.py#L52)
Like you described above,  I think there is a misunderstanding. 
_should I change the code as we are not concern about vote event with `option=other`?_

**Comment by jamesturk** [comment]
1. ah gotcha, I think we should include BillAction (like version, etc.) as things that only a scraper should add for now.  so let's keep these read-only 

2. yes I think there was a misunderstanding.  the intent of bad counts is any vote where:
counts.yes != len(votes.yes) or counts.no != len(votes.no) (etc.)

**Comment by mileswwatkins** [comment]
Think this has largely been completed, or is now the trajectory of the tool.
