### ISSUE TITLE
Create view for admin to see all changes

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#34]
(Related to https://github.com/openstates/admintools/issues/33, let's also wait on this until the application code is completed and merged in.)

**Comment by hiteshgarg14** [comment]
@mileswwatkins PR #28 is now ready to start work on this issue. 

_should I wait until you merge this PR or start working on it?_

**Comment by jamesturk** [comment]
as to not block you I think it'd be alright to start work on it, it might be good to use a second branch for this part
