### ISSUE TITLE
Public quality status server

### ISSUE THREAD

**Issue by estaub** [openstates/admintools#35]
It would be really nice to have a public server that shows summary metrics for each state/session.  I'm sure some of these are already in admintools, but in the absence of any doc (AFAICT), here are examples:

- most recent vote successfully scraped
- most recent bill update date/time
- per-chamber legislator-vs-seat validation: are there too many active legislators, or wildly too few?
- roll-call validation summary of summaries (I can explain if useful, but I suspect it'd be redundant) 
- number of unique motions
- size of largest bill title
- size of largest id
- number of legislators with missing <field> for several fields

Each of these metrics may have a static alarm level for each state.
And/or, some small amount of history should be retained and a delta view provided, with alarms for big regressions.

**Comment by jamesturk** [comment]
by summary of summaries are you referring to ensuring that yes_count=len(yes_votes)?

**Comment by jamesturk** [comment]
and can you clarify size of largest ID?

**Comment by estaub** [comment]
>> by summary of summaries are you referring to ensuring that yes_count=len(yes_votes)?

Often reporting each anomaly by itself would create a lot of spewage, so they need summation for usability.  A good example is the case of missing individual votes on roll calls, where a histogram might be used to summarize the number of missing individuals on each vote.  (Sometimes a few missing people is normal, but very often not.)

>> and can you clarify size of largest ID?

As with bill titles (see https://github.com/openstates/documentation/issues/6), other state-provided fields like motion and bill_id are often surprisingly verbose - to the point of near-uselessness.

**Comment by jamesturk** [comment]
we're going to be merging this project into new-openstates.org so closing this issue and reopened as openstates/meta#48
