### ISSUE TITLE
Substring search in entity lists not working

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#39]
Example, from PR #28

![substring-search](https://user-images.githubusercontent.com/4959135/28251995-03d1fd04-6a58-11e7-9d98-7eb88b884f81.gif)

**Comment by hiteshgarg14** [comment]
@mileswwatkins 
Do we want substring searches in all type of filters?

**Comment by mileswwatkins** [comment]
That'd make sense to me, to have substring, case-insensitive searches for all of these list-search fields.

Maybe there's a way to make the searching generic to avoid repetition.

**Comment by hiteshgarg14** [comment]
> Maybe there's a way to make the searching generic to avoid repetition.

Can you please explain, what do you mean by `repetition` here?
actually, an object will appear for only one time in table row when you will search (substring/case-insensitive)

**Comment by mileswwatkins** [comment]
Oh, I just mean to avoid code repetition; you should be able to reuse this case-insensitive substring-y search function.

**Comment by hiteshgarg14** [comment]
Oh! Cool.
then we are done with this issue in PR #41
