### ISSUE TITLE
How to deal with issue in name of main person object?

### ISSUE THREAD

**Issue by hiteshgarg14** [openstates/admintools#45]
In some, cases we have the wrong name in the main person object. as we can see in the screenshot that unmatched person name is correct but the name of main person object is wrong.

![screenshot from 2017-07-21 02 05 25](https://user-images.githubusercontent.com/19409253/28437763-7262c762-6db9-11e7-8fa4-88de53cc2ac6.png)

**Comment by jamesturk** [comment]
this is a good point, I'm not sure what to do.

I think the solution in general will have to be to fix the scraper (e.g. drop Chairman/Councilmember) which will either automatically resolve the issue or at least allow it to be resolved correctly (via a merge)

**Comment by mileswwatkins** [comment]
Good with @jamesturk's solution
