### ISSUE TITLE
Test performance using many years of data

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/admintools#51]
Right now, we're developing on a 2017-only database. If we want to use the admin tool on several years of data going forward, it'd be nice to see how it performs, as far as views, imports, and resolution.

Hitesh has already done a great job incorporating session-level filters into most/all relevant views, but could still get slowed down at other points.

@jamesturk, is this something that's possible, given all the old Billy data? Or is it just too dirty to get pupa2billy to run well enough, for the purposes of this testing?

**Comment by jamesturk** [comment]
we'd need billy2pupa for this, and that isn't really in a great place.  I'd say we table this and see how it does for 2017 and refactor/optimize as needed

once we're all merged up I can spend some time analyzing the queries using DDT to identify problem areas
