### ISSUE TITLE
avoid hard-coded path /admintools/

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#55]
instead of having /admintools/ be a hard-coded part of the URL let's have the app live wherever the upper-level urls.py mounts it.  in practice I think this will mean removing /admintools/ from urls.py (and then when including this in a Django project it would be included like ``` url(r'^admintools/', include('admintools.urls')),```

**Comment by hiteshgarg14** [comment]
yeah! that's the right way of doing it. :)
I kept it intentionally to make these app URLs independent of any integration.
