### ISSUE TITLE
issue count mismatch

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#56]
was playing w/ the admin today and noticed the numbers don't seem to match up when I go between the overview & the jurisdiction page

one:
<img width="1212" alt="nh" src="https://user-images.githubusercontent.com/8034/29297974-85c72834-8132-11e7-9b1a-392003872d7f.png">
two:
<img width="1091" alt="nh2" src="https://user-images.githubusercontent.com/8034/29297929-5740b3cc-8132-11e7-8494-885a856d34aa.png">

this confused me for a while but I realized that it is because Organization is split out into Membership/Post/etc.   -- we should consider:
- splitting these out on the first view
- combining the sections on the second view
- other options?

**Comment by hiteshgarg14** [comment]
> splitting these out on the first view

This was my initial thought. we can do this in two ways
   - We can make new columns for `memberships` and `posts`
   - We can keep the `organization` column and when user mouse over the count then we can show the post/membership related count via pop-up. like we did in `Last X Runs Failed`.
