### ISSUE TITLE
fix ordering of posts

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#57]
to more easily find what someone is looking for, should be sorted
<img width="1131" alt="post-order" src="https://user-images.githubusercontent.com/8034/29298239-534843b4-8134-11e7-8109-969b40c9ba0c.png">

**Comment by hiteshgarg14** [comment]
Sorry I didn't get this one. what do you mean by sorting here?

Do you mean sorting by `LABEL` like in descending order of `label`?
For now, members are sorted by `start_date` (newer person first)

**Comment by jamesturk** [comment]
yes, could we sort this by label (ascending 1-100,etc.)
