### ISSUE TITLE
retirement tool should be linked from 'too many members' view

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#58]
it'd be great if you could start the retirement process from the 'too many members' view instead of separately going to the retirement view to start to fix it

**Comment by hiteshgarg14** [comment]
Okay! what we can do this in two ways:-

-  as shown in screenshot user can enter the retirement date just near the legislator
![screenshot from 2017-08-15 14 21 41](https://user-images.githubusercontent.com/19409253/29309149-199a73e8-81c6-11e7-9acf-b2fd5f263ca5.png)

 - we can make legislator name as a link to retirement tool. something like this:-
  `http://127.0.0.1:8000/admintools/ocd-jurisdiction/country:us/state:nh/government/retire-legislators/?person=David+Doherty` 
 
Let me know what do you think. I will do that accordingly :)

**Comment by jamesturk** [comment]
let's go with the link, the date inline is interesting but I think it is rare enough that we can afford the click 👍
