### ISSUE TITLE
determine scope for user feedback tool

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#6]
- which models should it cover; just people, or more?
- where does it sit on the main website?
- how are reports stored? If in a database, what's the schema? 
- how are reports approved? What does the admin interface include?
- how are these patches applied? Do they ever go stale or obsolete?
- is there any attribution to the fixer? if so, where would this be stored?

**Comment by mileswwatkins** [comment]
@hiteshgarg14, added more questions to James's ones above ^

**Comment by hiteshgarg14** [comment]
The scope of User Feedback Tool:-
   - the user can report a wrong information on the website. (the user can also suggest a new value for the same.)
  - the user can suggest a value for a field having no value ie, None.

**Comment by hiteshgarg14** [comment]
**which models should it cover; just people, or more?**

As we discussed earlier, v1 of this tool should be based on `people`. we can launch v2 after getting feedback from other community members and experiencing bugs on v1. In v2 we can extend it to cover other models (mainly `organization` & `membership`).

**Comment by hiteshgarg14** [comment]
**where does it sit on the main website?**

We can have an `icon` on the bottom right side of the page which will float with the scroll bar(like we have `chat` option on many websites). when the user clicks on it then we can display a `Popup/Modal form` without redirecting the user to the new page.

**Comment by hiteshgarg14** [comment]
Before answering other question, Let's take a look at **The flow to report anything** goes like this,

  - when the user clicks on the `report` button. Then, we can fetch the appropriate `ocd database model` from the `urlpattern` of the particular page and display the `name/identifier` of person/org etc. This information will be there on the form automatically and the user can't modify it but the user can see it and verify that he/she is reporting about right legislator/org etc.

  - then the user will be asked to choose any one of the options
      - Report about the wrong detail
      - Suggest a missing information.

  - then next form field will be, a hard coded drop-down list which includes options like, `name`, `image`, `gender`, `birth_date`, `death_date`, `summary`, `national_identity`, `biography`, `email`, `postal address`, `voice`, `OTHER`.
       -  if the user chooses other than `other` field. then the form field for a new value for the selected field.
      - else user will be asked for the `title` of the field followed by a new value of that field.

  - then other fields like reporter's name, email id, sources, additional note.

**Comment by hiteshgarg14** [comment]
**how are reports stored? If in a database, what's the schema?**

we can have a separate DB table for these reports.
The important information to be stored is,
a) Reporter's Name & Email ID.
b) The `python-opencivic` database `Model` the report points to.
c) an optional `Note` TextField. (If reporter want to add some additional information)
d) type - `error` (if it's a wrong info) & `warning` (if it's a missing info)
e) jurisdiction it belongs to. (this will help us to filter results)
f) category (whether it is email or phone related/ other etc.)(this will help us to merge the suggested value to the related model.)
g) source [CharField](a note on the source of the information *required field.)
h) `new_value` suggested by user in CharField.
i) `old_value` in CharField (if exists else None)

**Comment by hiteshgarg14** [comment]
**how are reports approved? What does the admin interface include?**

(on state specific page there will be an option which will redirect to a new page)

Well, we have two `types` of reports for now. one is of type `error` and another one is `warning`. so there will be a filter to display any one of them.
Then, additional filters like, filter by reporter name, category, ocd-database model.

there will be a list of reports related to filtered objects. for eg. like `wrong detail` with category `email`. the table includes the columns for `new_value` , `old_value`, `reporter_name`, `reporter_email`, `note`, `sources` fields and `approve` or `discard` buttons.

**Comment by hiteshgarg14** [comment]
**how are these patches applied?**

if admin clicks on `discard` then report will be deleted from the DB table.
if admin clicks on `approve` then,
a) if the `category` field point to option other than `OTHER` then the we can merge that new_value with the original object and add that field into `locked_fields`.
b) else admin have to manually update this value in the admin-panel. there will be a link to redirect the admin user to go to that object directly.

**Comment by hiteshgarg14** [comment]
## Do they ever go stale or obsolete?

### Well, here comes the major drawback of one of the scopes of this tool

   -  if we are updating the `reported field` from `missing field` type then we can avoid adding that field into `locked_field` in this way if updated scraper starts scraping that value then it can be overwritten by new scraped value.

   -  **if we are updating the `reported field` from `wrong detail` type then it causes us the problem. because we will add the field into `locked_field`**

_I am really unable to find the solution to this problem. But at the same time, this forces me to re-think the scope of this tool.
considering the case (b)  a major drawback of this tool. let's consider this tool for just `missing fields` for now. in this way we can update the existing `dataquality_issues` DB table with new required fields and in case if that field gets an update from scrape then this will not cause any problem. **In this way we can also have this tool for objects other than `people` in v1.**_

**Comment by hiteshgarg14** [comment]
**Is there any attribution to the fixer? if so, where would this be stored?**

sorry but I am unable to understand this question. can you explain more?

**Comment by mileswwatkins** [comment]
We'll chat about all this at tomorrow's meeting!

cc @jamesturk @hiteshgarg14

**Comment by mileswwatkins** [comment]
So, let's start with this list of user-editable legislator fields, @hiteshgarg14:

- `name`
- `image`
- `contact_details`: `voice`, `email`, and `address` `type`s

@jamesturk, any other fields? I feel like those are the key ones!

**Comment by hiteshgarg14** [comment]
id  |  object_id      |  content_type_id  |  jurisdiction_id      |  status      |  old_value                    |  new_value                     |  category  |  alert    |  note       |  source                         |  reporter's email
----|-----------------|-------------------|-----------------------|--------------|-------------------------------|--------------------------------|------------|-----------|-------------|---------------------------------|------------------
1   |  Ocd-person/1   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  123-456-897                  |  123-789-888                   |  voice     |  error    |  some note  |  http://www.p1-voicesource.com  |  hitesh@gmail.com
2   |  Ocd-person/1   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  123-789-888                  |  14257-8952                    |  voice     |  error    |             |  http://www.p1-voicesource.com  |  garg@gmail.com
3   |  Ocd-person/1   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  78-98-52                     |  11-44-44                      |  voice     |  error    |             |  http://www.p1-voicesource.com  |  garg@gmail.com
4   |  Ocd-person/1   |  6                |  Ocd-jurisdiction/mo  |  approved    |  17597-0042-54                |  759700-4257                   |  voice     |  error    |             |  http://www.p1-voicesource.com  |  hitesh@gmail.com
5   |  Ocd-person/1   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  759700-4257                  |  451212-8787                   |  voice     |  error    |             |  www.p1-voice.com               |  hitesh@gmail.com
6   |  Ocd-person/1   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  759700-4257                  |  760042-57                     |  voice     |  error    |  some note  |  http://www.p1-voicesource.com  |  garg@gmail.com
7   |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  45@gmail.com                 |  46@gmail.com                  |  email     |  error    |             |  http://www.p2-email.com        |  garg@gmail.com
8   |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  46@gmail.com                 |  78@gmail.com                  |  email     |  error    |             |  http://www.p2-email.com        |  hitesh@gmail.com
9   |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  50@gmail.com                 |  55@gmail.com                  |  email     |  error    |             |  http://www.p2-email.com        |  garg@gmail.com
10  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  approved    |  30@gmail.com                 |  2@gmail.com                   |  email     |  error    |             |  http://www.p2-email.com        |  garg@gmail.com
11  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  2@gmail.com                  |  22@gmail.com                  |  email     |  error    |  some note  |  http://www.p2-email.com        |  garg@gmail.com
12  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  hitehg                       |  hiteshg                       |  name      |  error    |             |  http://www.p2-name.com         |  hitesh@gmail.com
13  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  hiteshgar                    |  hitesg                        |  name      |  error    |             |  http://www.p2-name.com         |  garg@gmail.com
14  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  hitesg                       |  Hitesh Garg                   |  name      |  error    |  some note  |  www.p2-name.com                |  hitesh@gmail.com
15  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  hitesg                       |  hiteshgarg                    |  name      |  error    |             |  http://www.p2-name.com         |  garg@gmail.com
16  |  Ocd-person/2   |  6                |  Ocd-jurisdiction/mo  |  approved    |  hitesg                       |  hg                            |  name      |  error    |             |  http://www.p2-name.com         |  garg@gmail.com
17  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  approved    |  ramg                         |  ram jr. G                     |  name      |  error    |             |  http://www.p3-name.com         |  hitesh@gmail.com
18  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  30@gmail.com                 |  3@gmail.com                   |  email     |  warning  |  some note  |  http://www.p3-email.com        |  garg@gmail.com
19  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  approved    |  1024-57412                   |  2587-5456                     |  voice     |  warning  |             |  http://www.p3-voice.com        |  garg@gmail.com
20  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  5874-21213                   |  2354-5                        |  voice     |  warning  |             |  http://www.p3-voice.com        |  garg@gmail.com
21  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  woodside                     |  new york                      |  address   |  error    |             |  http://www.p3-address.com      |  hitesh@gmail.com
22  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  new york                     |  china                         |  address   |  error    |             |  http://www.p3-address.com      |  garg@gmail.com
23  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  approved    |  dc                           |  vegas                         |  address   |  error    |  some note  |  http://www.p3-address.com      |  garg@gmail.com
24  |  Ocd-person/3   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  maine                        |  yoga                          |  address   |  error    |             |  http://www.p3-address.com      |  hitesh@gmail.com
25  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  http://www.oldimage.png      |  http://www.new-oldimage.png   |  image     |  error    |             |  http://www.p4-image.com        |  garg@gmail.com
26  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  http://www.new-oldimage.png  |  https://www.xyz-image.png     |  image     |  error    |             |  http://www.p4-image.com        |  hitesh@gmail.com
27  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  http://www.pqr-image.png     |  http://www.abc-image.png      |  image     |  error    |  some note  |  http://www.p4-image.com        |  garg@gmail.com
28  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  approved    |  http://www.wrong-image.png   |  http://www.right-image.ong    |  image     |  error    |             |  http://www.p4-image.com        |  garg@gmail.com
29  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  http://www.right-image.png   |  http://www.correct-image.png  |  image     |  error    |             |  http://www.p4-image.com        |  garg@gmail.com
30  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  dausa                        |  ajmer                         |  address   |  warning  |             |  www.p4-address.com             |  hitesh@gmail.com
31  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  unreviewed  |  dausa                        |  jaipur                        |  address   |  warning  |             |  http://p4-address.com          |  hitesh@gmail.com
32  |  Ocd-person/4   |  6                |  Ocd-jurisdiction/mo  |  deprecated  |  sikar                        |  kota                          |  address   |  warning  |  some note  |  http://p4-address.com          |  garg@gmail.com
33  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  approved    |  mathura                      |  agra                          |  address   |  warning  |             |  http://www.p5-address.com      |  garg@gmail.com
34  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  deprecated  |  farah                        |  mahua                         |  address   |  warning  |  some note  |  http://www.p5-address.com      |  hitesh@gmail.com
35  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  unreviewed  |  85475-551                    |  5514-5741                     |  voice     |  warning  |  some note  |  www.p5-voice.com               |  garg@gmail.com
36  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  deprecated  |  24@gmail.cm                  |  25@gmail.com                  |  email     |  error    |  some note  |  www.p5-email.com               |  garg@gmail.com
37  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  deprecated  |  25@gmail.com                 |  33@gmail.com                  |  email     |  error    |  some note  |  www.p5-email.com               |  hitesh@gmail.com
38  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  deprecated  |  42@gmail.com                 |  52@gmail.com                  |  email     |  error    |             |  www.p5-email.com               |  garg@gmail.com
39  |  Ocd-person/5   |  6                |  Ocd-jurisdiction/ny  |  approved    |  wrong@gmail.com              |  correct@gmail.com             |  email     |  error    |             |  www.p5-email.com               |  garg@gmail.com
40  |  Ocd-person/6   |  6                |  Ocd-jurisdiction/ny  |  approved    |  anjali                       |  ayushi                        |  name      |  error    |  some note  |  www.p6-name.com                |  hitesh@gmail.com
41  |  Ocd-person/6   |  6                |  Ocd-jurisdiction/ny  |  unreviewed  |  ayushi                       |  anshul                        |  name      |  error    |  some note  |  www.p6-name.com                |  hitesh@gmail.com





Cases Covered:-
1. If two users submitted the patch for same field ie, more than one `unreviewed` patches.
2. more than one `deprecated` patches.
3. `approved` patch.

**Comment by hiteshgarg14** [comment]
Instead of using `Person` as `ForeignKey`, I think it will be useful to use `content_type objects`.
what is your view on this?

**Comment by jamesturk** [comment]
this looks pretty good and GenericForeignKey/content_type makes sense to me

**Comment by mileswwatkins** [comment]
Alright, I think we've nailed down scope, going to close this ticket.
