### ISSUE TITLE
clarify (or remove) 'all' parameter to import management command

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#63]
right now this parameter is required via 

```parser.add_argument('all', nargs='+', type=str)```

but it doesn't seem to be used

**Comment by hiteshgarg14** [comment]
- `python manage.py import all` is a single command that can be used to import all types of data quality issues into DB.
   - `python manage.py import all --people` will import only people related data quality issues.
   - and so on.

Let me know if we don't need `all` positional argument

**Comment by hiteshgarg14** [comment]
removed `all` argument :)
