### ISSUE TITLE
data quality exceptions

### ISSUE THREAD

**Issue by jamesturk** [openstates/admintools#8]
after #1/#2 - to make these less noisy it should be easy to add data quality exceptions for 'known' issues

likely to differ from how we did things in billy since we've learned a lot about what exceptions we encounter

**Comment by hiteshgarg14** [comment]
This is reminder for me to follow the below-mentioned work flow:-
 -  Checking boxes next to as many items as you want to 'ignore'
 - Then typing in an explanation at the bottom 
 - and hitting a save button

Things to Consider:-
 - the 'ignore' status should survive a refresh
